# Generated by Django 5.1.5 on 2025-01-31 03:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='Xarajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('izoh', models.TextField()),
                ('sana', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
            },
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('narx1', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('narx2', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='mahsulotlar/')),
                ('miqdor', models.PositiveIntegerField(default=0)),
                ('olchov', models.CharField(choices=[('dona', 'Dona'), ('kg', 'KG'), ('ta', 'Ta')], default='dona', max_length=10)),
                ('brend', models.CharField(blank=True, max_length=100, null=True)),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='mainApp.bolim')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Kirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sana', models.DateField(auto_now_add=True)),
                ('narx', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.mahsulot')),
            ],
            options={
                'verbose_name': 'Kirim',
                'verbose_name_plural': 'Kirimlar',
            },
        ),
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('jami_summa', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sana', models.DateField(auto_now_add=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.mahsulot')),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
            },
        ),
    ]
